domain: demos.haus
image: prod-comms.ps5.docker-registry.canonical.com/demos.haus

env:
  - name: SENTRY_DSN
    value: https://8f10373e49b940c4b69225b132520ff0@sentry.is.canonical.com//27

  - name: IN_K8S_CLUSTER
    value: true

  - name: JENKINS_URL
    secretKeyRef:
      key: url
      name: webteam-jenkins

  - name: JENKINS_TOKEN
    secretKeyRef:
      key: demos-remote-build-token
      name: webteam-jenkins

  - name: GITHUB_ACCESS_TOKEN
    secretKeyRef:
      key: webapp-access-token
      name: github

  - name: GITHUB_WEBHOOK_SECRET
    secretKeyRef:
      key: demos-webook-secret
      name: github
  
  - name: JENKINS_PUBLIC_URL
    secretKeyRef:
      key: public_url
      name: webteam-jenkins
demo:
  replicas: 1
